name: youtube_id_scraper
description: A package to extract YouTube video IDs and other details from URLs.
version: 1.0.3
homepage: https://github.com/RaBi94567/youtube_id_scraper/

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

example: example.md
